### ISSUE TITLE
After playing against this engine, I got robbed

### ISSUE THREAD

**Issue by tosculptclouds** [NiranjanRobotics/goofy-chess-bot#1]
^

**Comment by NiranjanRobotics** [comment]
skill issue

**Comment by tosculptclouds** [comment]
WARNING to all new users, this is a scam developed to get you robbed !!!!!!!!!!!!!!!!!!!!!!!!!!!!
![ga991011](https://github.com/user-attachments/assets/e8fd90c4-7d81-4275-bbfe-96eafba221e8)
